server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    username: myuser
    password: mypass
  jpa:
    hibernate:
      ddl-auto: none          # Flyway controla o schema
    open-in-view: false       # Melhor prática para não manter session aberta na view
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public

logging:
  level:
    org.hibernate.SQL: debug        # mostra SQL (dev only)
    org.hibernate.type.descriptor.sql: trace
