CREATE TABLE IF NOT EXISTS event_participants (
    event_id BIGINT NOT NULL,
    user_id VARCHAR(120) NOT NULL,
    PRIMARY KEY (event_id, user_id),
    CONSTRAINT fk_event_participants_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_participants_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS avaliations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id BIGINT NOT NULL,
    from_user_id VARCHAR(120) NOT NULL,
    to_user_id VARCHAR(120) NOT NULL,
    status VARCHAR(20) NOT NULL,
    rating INTEGER,
    comment TEXT,
    requested_at TIMESTAMP,
    responded_at TIMESTAMP,
    CONSTRAINT fk_avaliations_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_avaliations_from_user FOREIGN KEY (from_user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_avaliations_to_user FOREIGN KEY (to_user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_avaliations_unique_pair UNIQUE (event_id, from_user_id, to_user_id)
);
