ALTER TABLE users
ADD COLUMN IF NOT EXISTS total_skill INTEGER;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS total_received_evaluations INTEGER DEFAULT 0;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS total_rating INTEGER DEFAULT 0;
