version: "3.9"
services:
  postgres:
<<<<<<< HEAD
    image: postgres:latest
    container_name: myapp-postgres
=======
    image: postgres:16
    container_name: myapp-postgres
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
>>>>>>> parent of 54d1e99 (Merge branch 'dev' into origin/feat/back-amizade)
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass